### ISSUE TITLE
Index Error on "save and continues" with existing subscribe list

### ISSUE THREAD

**Issue by petrikoz** [ITCase-django/django-unisender#48]
After click "Save and continue" with existing instance of model SubscribeList in admin, raise error:

``` pytb
IndexError: list index out of range
...
Traceback (most recent call last):
  File "/home/petr/work/.venv/angio/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 113, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/petr/work/.venv/angio/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 372, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/petr/work/.venv/angio/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/petr/work/.venv/angio/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 89, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/petr/work/.venv/angio/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 202, in inner
    return view(request, *args, **kwargs)
  File "/home/petr/work/itcase/github/django-unisender/project_files/unisender/admin.py", line 195, in change_view
    request, object_id, form_url, extra_context)
  File "/home/petr/work/.venv/angio/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/petr/work/.venv/angio/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/petr/work/.venv/angio/local/lib/python2.7/site-packages/django/utils/decorators.py", line 21, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/petr/work/.venv/angio/local/lib/python2.7/site-packages/django/db/transaction.py", line 223, in inner
    return func(*args, **kwargs)
  File "/home/petr/work/.venv/angio/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1106, in change_view
    self.save_related(request, form, formsets, True)
  File "/home/petr/work/itcase/github/django-unisender/project_files/unisender/admin.py", line 205, in save_related
    instance = formsets[0].queryset[0]
  File "/home/petr/work/.venv/angio/local/lib/python2.7/site-packages/django/db/models/query.py", line 231, in __getitem__
    return list(qs)[0]
IndexError: list index out of range
```

**Comment by mr-africa** [comment]
This bug fix in new release
